live_config_reload = true

[window]
decorations = "transparent"
opacity = 0.75

[window.padding]
top = 30
left = 15
right = 10
bottom = 0

[font]
size = 14

[font.bold]
family = "Sarasa Term K Nerd Font"
style = "Bold"

[font.normal]
family = "Sarasa Term K Nerd Font"
style = "Regular"

[font.offset]
y = 5

[colors.normal]
black =   "0x002221"
red =     "0xea3431"
green =   "0x00b6b6"
yellow =  "0xf8b017"
blue =    "0x4894fd"
magenta = "0xe01dca"
cyan =    "0x1ab2ad"
white =   "0x99dddb"

[colors.bright]
black =   "0x006562"
red =     "0xea3431"
green =   "0x00b6b6"
yellow =  "0xf8b017"
blue =    "0x4894fd"
magenta = "0xe01dca"
cyan =    "0x1ab2ad"
white =   "0xe6f6f6"

[scrollbar]
mode = "Fading"
color = "#ffffff"
opacity = 0.3
